site_name: AI Classification Standard
site_description: An open framework for classifying and evaluating artificial intelligence systems
site_author: AICS Community
repo_url: https://github.com/4hum-ai/aics
repo_name: Github
site_url: https://4hum-ai.github.io/aics/
use_directory_urls: true
nav:
  - Home: index.md
  - Taxonomy:
    - Overview: taxonomy.md
    - Infrastructure (INF): taxonomy/inf.md
    - Models & Platforms (MOD): taxonomy/mod.md
    - Applications (APP): taxonomy/app.md
    - Governance (GOV): taxonomy/gov.md
  - Standard Mappings: mappings.md
  - Company Registry: registry.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
